import {
  pgTable,
  uuid,
  text,
  timestamp,
  boolean,
  integer,
  jsonb,
  index,
  pgEnum,
  foreignKey,
} from 'drizzle-orm/pg-core'
import { companies, users } from './tenancy'
import { chartAccounts, financialAccounts } from './accounting'

/**
 * What happens when a rule matches (spec §3): either the transaction is
 * categorized outright, or a suggestion is offered for the user to confirm.
 * Recurring vendor memory is created as a `suggest` rule and can be promoted
 * to `auto` once the user confirms they want it applied without review.
 */
export const ruleActionEnum = pgEnum('rule_action', ['auto', 'suggest'])

/** Comparison operators available to rule conditions. */
export const RULE_OPERATORS = [
  'contains',
  'not_contains',
  'equals',
  'not_equals',
  'starts_with',
  'ends_with',
  'gt',
  'gte',
  'lt',
  'lte',
] as const

export type RuleOperator = (typeof RULE_OPERATORS)[number]

/** Transaction fields a rule can test. */
export const RULE_FIELDS = [
  'description',
  'merchantName',
  'amountCents',
  /** Absolute value of the amount — the natural way to express "over $100". */
  'absAmountCents',
  'financialAccountId',
  'direction',
] as const

export type RuleField = (typeof RULE_FIELDS)[number]

export type RuleCondition = {
  field: RuleField
  operator: RuleOperator
  /** Strings compare case-insensitively; numbers are cents. */
  value: string | number
}

/**
 * A user-created categorization rule (spec §3). Conditions are combined with
 * `matchType`, so a rule can require every condition or any of them.
 */
export const categorizationRules = pgTable(
  'categorization_rules',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    companyId: uuid('company_id')
      .notNull()
      .references(() => companies.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    /** Lower numbers win. Ties break on creation time, oldest first. */
    priority: integer('priority').notNull().default(100),
    matchType: text('match_type', { enum: ['all', 'any'] })
      .notNull()
      .default('all'),
    conditions: jsonb('conditions').$type<RuleCondition[]>().notNull(),

    /** Target GL account applied on match. */
    chartAccountId: uuid('chart_account_id')
      .notNull()
      .references(() => chartAccounts.id, { onDelete: 'cascade' }),
    action: ruleActionEnum('action').notNull().default('suggest'),
    /** Optionally restrict the rule to one bank account. */
    financialAccountId: uuid('financial_account_id'),

    /**
     * True when this rule was generated by recurring vendor memory rather than
     * authored by hand — surfaced differently in the UI.
     */
    isVendorMemory: boolean('is_vendor_memory').notNull().default(false),
    isActive: boolean('is_active').notNull().default(true),

    matchCount: integer('match_count').notNull().default(0),
    lastAppliedAt: timestamp('last_applied_at', { withTimezone: true }),

    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    companyActiveIdx: index('categorization_rules_company_active_idx').on(
      t.companyId,
      t.isActive,
      t.priority,
    ),
    // Named explicitly: the generated name would exceed Postgres's 63-byte
    // identifier limit and be silently truncated.
    financialAccountFk: foreignKey({
      name: 'categorization_rules_financial_account_fk',
      columns: [t.financialAccountId],
      foreignColumns: [financialAccounts.id],
    }).onDelete('cascade'),
  }),
)
