-- Phase 165: where an asset came from, and what must be said about it.
--
-- ADR 0164's audit found two of spec §11's seven AI capabilities missing and
-- nominated **AI Design Assistant** first, for a specific reason: §11 asks it to
-- "generate layout suggestions, brand-consistent variations,
-- background/graphic concepts, image prompts, and logo ideation; **preserve user
-- control and provenance**" -- and provenance is a data decision that should be
-- settled before a prompt is written.
--
-- ## What measuring found
--
-- **User control already exists and is well made.** `ai_suggestions` carries an
-- accept/reject decision, and `suggestions.ts` says why it records the person:
--
--   the *person* who accepted, not the model, because the person is who decided
--
-- **Provenance does not exist, and `ai_requests` is not it.** That table is
-- §12's *usage ledger* -- tenant, user, feature, provider, model, tokens, cost,
-- latency, outcome. It records that a request happened and what it cost. It does
-- not record what was produced or where what was produced ended up. Conflating
-- the two is how a product ends up able to bill for a generated image and unable
-- to say which client proposal it is sitting in.
--
-- ## Two findings this migration is shaped by
--
-- **1. `assets.uploaded_by` encodes an assumption that is about to become
-- false.** Every asset today was uploaded by a person, so a nullable
-- `uploaded_by` and no provenance column together say "a person put this here".
-- The first asset a Design Assistant produces makes that a false declaration on
-- every row carrying it -- Phase 110 and 125's defect, in the table whose
-- contents get emailed to clients.
--
-- Which is also why the backfill below can **assert** rather than guess: every
-- existing row genuinely was uploaded by a person, so `'uploaded'` is a measured
-- fact and not a default chosen for convenience. Compare Phase 157, which
-- declined to backfill because what it would have asserted was never recorded.
--
-- **2. Provenance that does not propagate is true once and false forever
-- after.** §11 asks for "brand-consistent variations". A variation of an
-- AI-generated background is itself AI-derived; a flyer built from it contains
-- AI-generated material; the proposal that embeds the flyer reaches a client.
-- `assets` had no derivation relationship at all -- nothing was derived from
-- anything -- so the moment the assistant exists the chain it creates would have
-- nowhere to be recorded.
--
-- The chain, measured: `assets` -> a block's `asset_id` -> `design_documents`
-- -> the rendered proposal -> a client.

ALTER TABLE assets
  -- One of `PROVENANCE_ORIGINS` in `modules/ai/provenance.ts`, as text. ADR
  -- 0033's rule for registry keys: the register is code, and a foreign key to a
  -- table of names pointing at code is a foreign key to something that may not
  -- exist.
  ADD COLUMN provenance_origin text NOT NULL DEFAULT 'uploaded',

  -- The usage-ledger row behind a machine origin. What makes the claim
  -- checkable: without it, "this was generated by AI" is an assertion about
  -- something nothing recorded.
  ADD COLUMN ai_request_id uuid REFERENCES ai_requests(id) ON DELETE SET NULL,

  -- What it was made from. ON DELETE SET NULL rather than CASCADE: deleting the
  -- background a flyer was built from must not delete the flyer, and the flyer's
  -- own `provenance_origin` already carries the disclosure forward -- which is
  -- the point of taking the join when it is derived rather than looking the
  -- parent up later.
  ADD COLUMN derived_from_id uuid REFERENCES assets(id) ON DELETE SET NULL,

  ADD CONSTRAINT assets_provenance_origin_known CHECK (
    provenance_origin IN ('uploaded', 'authored', 'ai-assisted', 'ai-generated')
  ),

  -- The constraint the whole phase turns on, and it is deliberately
  -- bidirectional.
  --
  -- A machine origin **requires** a request: an artifact claiming to be
  -- AI-generated with nothing in the ledger behind it is a declaration argued
  -- from a fact that is not a fact.
  --
  -- A human origin **forbids** one, and that is the direction that matters:
  -- without it, a row could carry an AI request and be disclosed as human-made.
  -- A check beats a convention and a constraint beats a check (Phase 116), so
  -- the database refuses both rather than `provenanceStands` being remembered.
  ADD CONSTRAINT assets_provenance_matches_request CHECK (
    (provenance_origin IN ('ai-assisted', 'ai-generated') AND ai_request_id IS NOT NULL)
    OR (provenance_origin IN ('uploaded', 'authored') AND ai_request_id IS NULL)
  ),

  -- An asset derived from itself is a cycle of one, and the only cycle a single
  -- CHECK can see. Longer ones are refused by `deriveAsset`, which walks the
  -- chain -- said here so the gap is stated rather than looked for.
  ADD CONSTRAINT assets_not_derived_from_self CHECK (derived_from_id IS DISTINCT FROM id);

-- Read when a document is rendered, to work out what it has to disclose.
CREATE INDEX assets_derived_from_idx ON assets (company_id, derived_from_id)
  WHERE derived_from_id IS NOT NULL;

--------------------------------------------------------------------------------
-- The default, and why it is dropped again.
--
-- `DEFAULT 'uploaded'` makes the ALTER cheap and backfills every existing row
-- with a fact rather than a guess. Keeping it afterwards would be the problem:
-- a Design Assistant that forgot to set the origin would get `'uploaded'`
-- silently, which is precisely the false declaration this migration exists to
-- prevent, reintroduced as a convenience.
--
-- So the default goes, and `uploadAsset` says `'uploaded'` explicitly. A new
-- insert that omits the column now fails loudly.

ALTER TABLE assets ALTER COLUMN provenance_origin DROP DEFAULT;

--------------------------------------------------------------------------------
-- The feature value the ledger had no room for.
--
-- Found by writing the test: `ai_feature` lists eight values -- four
-- bookkeeping, reconciliation, proposal, marketing, insights -- which is §11's
-- five implemented capabilities and no more. There is no value for a design
-- generation.
--
-- That matters here rather than in the phase that builds the assistant, because
-- `assets.ai_request_id` is what makes a machine origin checkable: an
-- `ai-generated` asset must point at a ledger row saying what produced it. With
-- no enum value for design, there was no honest way to write that row at all --
-- so the provenance column could never have been populated, and the CHECK above
-- would have made that failure loud instead of silent, which is the right
-- outcome and not a usable one.
--
-- `design` only. `strategic_account` is §11's other missing capability and gets
-- its value in the phase that builds it, because a value with no producer is
-- the thing Phase 147 and Phase 157 argued about and the rule they settled is
-- that an unused declaration is kept when it accuses and deleted when it
-- excuses. This one would do neither yet.

ALTER TYPE ai_feature ADD VALUE IF NOT EXISTS 'design';
