import { beforeEach, describe, expect, it } from 'vitest'
import { eq } from 'drizzle-orm'
import { db } from '@/db'
import { aiRequests, assets } from '@/db/schema'
import {
  PROVENANCE_ORIGINS,
  derivedProvenance,
  disclosureFor,
  documentDisclosure,
  originFor,
  provenanceStands,
  strongerOf,
  type Provenance,
  type ProvenanceOrigin,
} from '@/modules/ai/provenance'
import { disclosureForDocument } from '@/modules/design/documents'
import { createMarketingDocument, saveDocument } from '@/modules/design/documents'
import { uploadAsset } from '@/modules/studio/assets'
import { RegistryError } from '@/modules/errors/registry'
import { createCompanyFixture, type Fixture } from './helpers'

/**
 * What the client is told (Phase 165).
 *
 * ADR 0164's audit found two of spec §11's seven AI capabilities missing and
 * nominated **AI Design Assistant** first, because §11 asks it to *"preserve
 * user control and provenance"* and provenance is a data decision that should be
 * settled before a prompt is written.
 *
 * Measuring found that **control already exists and provenance does not.**
 * `ai_suggestions` records the accept/reject with the person who decided, as
 * `suggestions.ts` says in those words. `ai_requests` is §12's *usage ledger* —
 * tokens, cost, latency — and records nothing about what was produced or where
 * it ended up.
 *
 * So this phase is the data decision, and the two rules it turns on:
 *
 * 1. **Provenance that does not propagate is true once and false forever
 *    after.** A crop of an AI-generated image is a crop of AI-generated
 *    material.
 * 2. **A disclosure the author can edit out is not a disclosure.** Hence its own
 *    field on the render input rather than appended to the footer.
 */

let fixture: Fixture

beforeEach(async () => {
  fixture = await createCompanyFixture({ name: 'Marchetti Design' })
})

/** A usage-ledger row, so a machine origin has something real behind it. */
async function anAiRequest(): Promise<string> {
  const [row] = await db
    .insert(aiRequests)
    .values({
      companyId: fixture.companyId,
      userId: fixture.userId,
      feature: 'design',
      promptKey: 'design.background',
      promptVersion: 1,
      provider: 'mock',
      model: 'mock-1',
      outcome: 'ok',
    })
    .returning({ id: aiRequests.id })

  return row.id
}

/**
 * The constraint a write violated.
 *
 * On the driver error's `cause` rather than in its message, which is ADR 0074's
 * whole point: the sentence a person would see carries none of this, and the
 * fact that ends the problem in a minute lives one level down. Phase 158's
 * export-log test learned the same thing.
 */
async function refusedBy(write: Promise<unknown>): Promise<string | undefined> {
  return write.then(
    () => undefined,
    (error: unknown) => (error as { cause?: { constraint_name?: string } }).cause?.constraint_name,
  )
}

describe('the lattice ranks disclosure, not credit', () => {
  it('keeps a parent’s disclosure through a child’s edit', () => {
    /**
     * The rule the whole module exists for. A person who heavily edits an
     * AI-generated image has done most of the work and the file still contains
     * AI-generated material — which is what a client, a regulator or a stock
     * licence cares about.
     *
     * `authored` would be true about what they did and false about what the file
     * contains, and the file is what reaches the client.
     */
    expect(strongerOf('authored', 'ai-generated')).toBe('ai-generated')
    expect(strongerOf('ai-generated', 'authored')).toBe('ai-generated')
    expect(strongerOf('ai-assisted', 'ai-generated')).toBe('ai-generated')
    expect(strongerOf('uploaded', 'authored')).toBe('authored')

    const derived = derivedProvenance(
      { origin: 'ai-generated', id: 'parent-id' },
      { origin: 'authored', aiRequestId: null, derivedFromId: null },
    )

    expect(derived.origin).toBe('ai-generated')
    expect(derived.derivedFromId).toBe('parent-id')
  })

  it('says nothing about a human origin and something about a machine one', () => {
    expect(disclosureFor('uploaded')).toBeNull()
    expect(disclosureFor('authored')).toBeNull()
    expect(disclosureFor('ai-assisted')).toContain('AI assistance')
    expect(disclosureFor('ai-generated')).toBe('This was generated by AI.')
  })

  it('discloses a whole document by the strongest thing in it', () => {
    // An artifact is as disclosable as the most disclosable thing it is made of,
    // which is why this takes a list.
    expect(documentDisclosure([])).toBeNull()
    expect(documentDisclosure(['uploaded', 'authored'])).toBeNull()
    expect(documentDisclosure(['uploaded', 'ai-generated', 'authored'])).toBe(
      'This was generated by AI.',
    )
    expect(documentDisclosure(['uploaded', 'ai-assisted'])).toContain('AI assistance')
  })

  it('declares four origins, each with its own argument', () => {
    expect(PROVENANCE_ORIGINS).toHaveLength(4)

    for (const definition of PROVENANCE_ORIGINS) {
      expect(definition.because.length, definition.origin).toBeGreaterThan(80)
      // A machine origin must disclose something; a human one must not.
      expect(Boolean(definition.disclosure), definition.origin).toBe(definition.machineInvolved)
    }

    expect(() => originFor('ai-ish')).toThrow(RegistryError)
    expect(() => originFor('ai-ish')).toThrow(/not a free-text value on a row/)
  })
})

describe('the coherence rule, and the direction that matters', () => {
  it('refuses a machine origin with nothing in the ledger behind it', () => {
    const faults = provenanceStands({
      origin: 'ai-generated',
      aiRequestId: null,
      derivedFromId: null,
    })

    expect(faults).toHaveLength(1)
    expect(faults[0]).toContain('names no AI request')
  })

  it('refuses a human origin that carries one, which is the dangerous way round', () => {
    /**
     * Both directions are refused and they are not equally bad. A missing
     * request makes a claim uncheckable; a *present* request on a human origin
     * would let AI-generated material be disclosed as human-made.
     */
    const faults = provenanceStands({
      origin: 'uploaded',
      aiRequestId: 'some-request',
      derivedFromId: null,
    })

    expect(faults).toHaveLength(1)
    expect(faults[0]).toContain('disclosed as human-made')
  })

  it('accepts the two coherent shapes', () => {
    const human: Provenance = { origin: 'authored', aiRequestId: null, derivedFromId: null }
    const machine: Provenance = { origin: 'ai-assisted', aiRequestId: 'req', derivedFromId: null }

    expect(provenanceStands(human)).toEqual([])
    expect(provenanceStands(machine)).toEqual([])
  })
})

describe('the database refuses the same two shapes', () => {
  it('will not store a machine origin without a request', async () => {
    // A constraint beats a check (Phase 116): `provenanceStands` can be
    // forgotten and this cannot.
    expect(
      await refusedBy(
        db.insert(assets).values({
          companyId: fixture.companyId,
          filename: 'generated.png',
          contentType: 'image/png',
          sizeBytes: 100,
          storageProvider: 'database',
          storageKey: `${fixture.companyId}/no-request`,
          provenanceOrigin: 'ai-generated',
          aiRequestId: null,
        }),
      ),
    ).toBe('assets_provenance_matches_request')
  })

  it('will not store a human origin that carries one', async () => {
    const requestId = await anAiRequest()

    expect(
      await refusedBy(
        db.insert(assets).values({
          companyId: fixture.companyId,
          filename: 'claimed-human.png',
          contentType: 'image/png',
          sizeBytes: 100,
          storageProvider: 'database',
          storageKey: `${fixture.companyId}/claimed-human`,
          provenanceOrigin: 'uploaded',
          aiRequestId: requestId,
        }),
      ),
    ).toBe('assets_provenance_matches_request')
  })

  it('will not store an origin nobody declared, by either of two routes', async () => {
    /**
     * Refused by **both** constraints, which is worth recording rather than
     * narrowing the assertion to hide.
     *
     * `assets_provenance_origin_known` is the obvious one. But
     * `assets_provenance_matches_request` enumerates the four valid origins on
     * both of its branches — a machine origin with a request, or a human origin
     * without one — so an unknown value is in neither branch and fails that too.
     * It is doing double duty as a whitelist, and Postgres reports whichever it
     * evaluates first.
     *
     * So the assertion is that one of the two refused it, not which. Pinning the
     * name would be asserting an evaluation order nothing promises.
     */
    const refusal = await refusedBy(
      db.insert(assets).values({
        companyId: fixture.companyId,
        filename: 'vibes.png',
        contentType: 'image/png',
        sizeBytes: 100,
        storageProvider: 'database',
        storageKey: `${fixture.companyId}/vibes`,
        provenanceOrigin: 'mostly-ai',
        aiRequestId: null,
      }),
    )

    expect([
      'assets_provenance_origin_known',
      'assets_provenance_matches_request',
    ]).toContain(refusal)
  })

  it('will not let an asset be derived from itself', async () => {
    const asset = await uploadAsset(fixture.ctx, {
      filename: 'logo.png',
      contentType: 'image/png',
      data: Buffer.from('a-tiny-file'),
    })

    expect(
      await refusedBy(
        db.update(assets).set({ derivedFromId: asset.id }).where(eq(assets.id, asset.id)),
      ),
    ).toBe('assets_not_derived_from_self')
  })
})

describe('an upload says where it came from, because the default was dropped', () => {
  it('records a person’s file as uploaded, explicitly', async () => {
    /**
     * The migration gave the column a default so the backfill could assert a
     * measured fact — every existing asset genuinely was uploaded by a person —
     * and then **dropped the default**, so a caller that forgets fails loudly
     * instead of silently claiming a human origin.
     *
     * The compiler caught `uploadAsset` the moment the column existed, which is
     * the constraint working before any test ran.
     */
    const asset = await uploadAsset(fixture.ctx, {
      filename: 'headshot.png',
      contentType: 'image/png',
      data: Buffer.from('bytes-of-a-photo'),
    })

    const [row] = await db
      .select({
        origin: assets.provenanceOrigin,
        requestId: assets.aiRequestId,
        derived: assets.derivedFromId,
        uploadedBy: assets.uploadedBy,
      })
      .from(assets)
      .where(eq(assets.id, asset.id))

    expect(row.origin).toBe('uploaded')
    expect(row.requestId).toBeNull()
    expect(row.derived).toBeNull()
    // And `uploaded_by` still means what it says, which it would not have once
    // something could produce an asset nobody uploaded.
    expect(row.uploadedBy).toBe(fixture.userId)
  })
})

describe('what reaches the client', () => {
  it('discloses nothing for a document of human assets', async () => {
    const asset = await uploadAsset(fixture.ctx, {
      filename: 'photo.png',
      contentType: 'image/png',
      data: Buffer.from('a-photograph'),
    })

    const document = await createMarketingDocument(fixture.ctx, { name: 'Capability one-sheet' })
    await saveDocument(fixture.ctx, document.id, {
      blocks: [{ id: 'b1', type: 'image', assetId: asset.id, align: 'left' }],
    })

    expect(await disclosureForDocument(fixture.companyId, document.id)).toBeNull()
  })

  it('discloses a generated asset, through the chain to the document', async () => {
    /**
     * The chain this phase measured: an asset is referenced by a block's
     * `assetId`, the blocks are a document, the document is rendered into a
     * proposal, and the proposal is sent. A disclosure that stopped at the asset
     * row would be true and invisible.
     */
    const requestId = await anAiRequest()

    const [generated] = await db
      .insert(assets)
      .values({
        companyId: fixture.companyId,
        filename: 'background.png',
        contentType: 'image/png',
        sizeBytes: 2048,
        storageProvider: 'database',
        storageKey: `${fixture.companyId}/generated-background`,
        provenanceOrigin: 'ai-generated',
        aiRequestId: requestId,
      })
      .returning({ id: assets.id })

    const human = await uploadAsset(fixture.ctx, {
      filename: 'logo.png',
      contentType: 'image/png',
      data: Buffer.from('the-real-logo'),
    })

    const document = await createMarketingDocument(fixture.ctx, { name: 'Flyer' })
    await saveDocument(fixture.ctx, document.id, {
      blocks: [
        { id: 'b1', type: 'image', assetId: human.id, align: 'left' },
        { id: 'b2', type: 'image', assetId: generated.id, align: 'left' },
      ],
    })

    // One generated background in a document of otherwise human work still
    // discloses, because an artifact is as disclosable as the most disclosable
    // thing in it.
    expect(await disclosureForDocument(fixture.companyId, document.id)).toBe(
      'This was generated by AI.',
    )
  })

  it('cannot be edited out of the footer, because it is not in the footer', async () => {
    /**
     * The second rule. `RenderInput.disclosureText` is its own field, so an
     * author rewriting `footerText` cannot remove it — and the layout draws it
     * on its own line above the footer rather than mixed into the author's
     * words.
     *
     * Asserted from the source, because the alternative is a screenshot test of
     * a PDF and the thing worth protecting is the separation rather than the
     * pixels.
     */
    const { readFileSync } = await import('node:fs')
    const service = readFileSync('src/modules/pdf/service.ts', 'utf8')
    const layout = readFileSync('src/modules/pdf/layout.ts', 'utf8')

    expect(service).toContain('disclosureText: await disclosureForDocument(')
    // Not appended to the author's footer anywhere.
    expect(service).not.toMatch(/footerText:[^\n]*disclosure/i)
    expect(layout).toContain('input.disclosureText?.trim()')
    // And it reserves footer space on its own, so a document with only a
    // disclosure still gets a footer band to draw it in.
    expect(layout).toContain("Boolean(input.disclosureText?.trim())")
  })

  it('discloses nothing when a document embeds no assets at all', async () => {
    const document = await createMarketingDocument(fixture.ctx, { name: 'Text only' })
    await saveDocument(fixture.ctx, document.id, {
      blocks: [{ id: 'b1', type: 'heading', text: 'Our services', align: 'left' }],
    })

    expect(await disclosureForDocument(fixture.companyId, document.id)).toBeNull()
  })
})
